Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true  
    config.vm.define "mysql_vm" do |mysql|
        mysql.vm.box = "geerlingguy/centos7"
        mysql.vm.hostname = "db01"
        mysql.vm.network "private_network", ip: "192.168.32.5"
        mysql.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-N 7260"
        mysql.vm.provision :shell, path: "mysql.sh"
    end
    config.vm.define "memcached_vm" do |memcached|
        memcached.vm.box = "geerlingguy/centos7"
        memcached.vm.hostname = "mc01"
        memcached.vm.network "private_network", ip: "192.168.32.4"
        memcached.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-N 7260"
        memcached.vm.provision :shell, path: "memcached.sh"
    end
    config.vm.define "rabbitmq_vm" do |rabbitmq|
        rabbitmq.vm.box = "geerlingguy/centos7"
        rabbitmq.vm.hostname = "rmq01"
        rabbitmq.vm.network "private_network", ip: "192.168.32.3"
        rabbitmq.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-N 7260"
        rabbitmq.vm.provision :shell, path:"rabbitmq.sh"
    end
    config.vm.define "tomcat_vm" do |tomcat|
        tomcat.vm.box = "geerlingguy/centos7"
        tomcat.vm.hostname = "app01"
        tomcat.vm.network "private_network", ip: "192.168.32.2"
        tomcat.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-N 7260"
        tomcat.vm.provider "virtualbox" do |vb|
                vb.memory = "1024"
            end     
        tomcat.vm.provision :shell, path:"tomcat.sh"     
    end
    config.vm.define "nginx_vm" do |nginx|
        nginx.vm.box = "ubuntu/bionic64"
        nginx.vm.hostname = "web01"
        nginx.vm.network "private_network", ip: "192.168.32.6"
        nginx.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-N 7260"
        nginx.vm.provider "virtualbox" do |vb|
                vb.memory = "1024"
            end
        nginx.vm.provision :shell, path:"nginx.sh"
    end
end